# Generated by Django 3.1.4 on 2021-01-31 07:53

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('interviewee', models.CharField(max_length=128, verbose_name='인터뷰 대상자')),
                ('content', models.TextField(verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='공감수')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': '인터뷰',
                'verbose_name_plural': '인터뷰',
                'db_table': '인터뷰',
                'permissions': [('can_write_interview', 'Can Write Interview')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('content', models.TextField(verbose_name='댓글 입력')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.interview', verbose_name='인터뷰')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': '댓글',
            },
        ),
    ]
